### ISSUE TITLE
Publishing JVM libraries

### ISSUE THREAD

**Issue by gazanfarov** [touchlab/KMMBridge#155]
Is it possible to use KMM Bridge to publish JVM target?

Thank you.

**Comment by gazanfarov** [comment]
Never mind
Have figured out a way myself
In build.gradle of allshared module from example I have just put this settings:

```
kotlin {
    ios()
    jvm {
        withJava()
        val jvmJar by tasks.getting(org.gradle.jvm.tasks.Jar::class) {
            doFirst {
                duplicatesStrategy = DuplicatesStrategy.EXCLUDE

                manifest {
                    attributes["Main-Class"] = "ua.blink.telegram.ApplicationKt"
                }

                from(
                    configurations.getByName("runtimeClasspath")
                        .map { if (it.isDirectory) it else zipTree(it) }
                )
            }
        }
    }
 }
```

And in AllPublish GitHub action I have added next config:

```
name: All Publish
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"
jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6
    with:
      publishTask: kmmBridgePublish publishAndroidDebugPublicationToGitHubPackagesRepository publishAndroidReleasePublicationToGitHubPackagesRepository publishJvmPublicationToGitHubPackagesRepository
```
